---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ratelimit
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ratelimit
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60